using System;
using Softcoinp.ERP.Domain.Enums;

namespace Softcoinp.ERP.Domain.Entities;

public class ManagementReportSection
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string TenantId { get; set; } = string.Empty;

    public int SectionOrder { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public SectionStatus Status { get; set; } = SectionStatus.Pending;

    public string? AutoGeneratedQuery { get; set; }
    public DateTime? LastAutoGeneratedAt { get; set; }
    public DateTime? LastManualEditAt { get; set; }
    public string? LastEditedByUserId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
}
