import apiClient from './api-client';

export interface ReportCatalogItem {
  code: string;
  name: string;
  description: string;
  category: string;
  availableFormats: string[];
  containsPersonalData: boolean;
}

export interface GenerateReportRequest {
  reportTypeCode: string;
  format: string;
  periodFrom?: string;
  periodTo?: string;
  parameters?: Record<string, string>;
  notes?: string;
}

export interface GeneratedReport {
  id: string;
  reportTypeId: string;
  reportTypeName: string;
  reportTypeCode: string;
  format: string;
  periodFrom?: string;
  periodTo?: string;
  fileName: string;
  fileSizeBytes: number;
  generatedByUserId: string;
  generatedAt: string;
  parameters?: Record<string, string>;
  notes?: string;
  recurringConfigId?: string;
}

export interface RecurringReportConfig {
  id: string;
  reportTypeId: string;
  reportTypeName: string;
  name: string;
  frequency: string;
  format: string;
  recipientEmails: string[];
  subjectTemplate?: string;
  bodyTemplate?: string;
  lastExecutionAt?: string;
  nextExecutionAt?: string;
  status: string;
  createdAt: string;
}

export interface CreateRecurringReportConfigRequest {
  reportTypeCode: string;
  name: string;
  frequency: string;
  format: string;
  recipientEmails: string[];
  subjectTemplate?: string;
  bodyTemplate?: string;
}

export interface ManagementReportSection {
  id: string;
  sectionOrder: number;
  title: string;
  content: string;
  status: string;
  autoGeneratedQuery?: string;
  lastAutoGeneratedAt?: string;
  lastManualEditAt?: string;
  lastEditedByUserId?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface UpdateManagementReportSection {
  title?: string;
  content?: string;
  sectionOrder?: number;
}

export interface PDFTemplate {
  id: string;
  reportTypeCode: string;
  reportTypeName: string;
  logoFilePath?: string;
  headerText: string;
  footerText: string;
  signatureName: string;
  signatureRole: string;
  confidentialityNote?: string;
  disclaimerNote?: string;
  primaryColor: string;
  secondaryColor: string;
  isDefault: boolean;
}

export interface UpdatePDFTemplate {
  logoFilePath?: string;
  headerText?: string;
  footerText?: string;
  signatureName?: string;
  signatureRole?: string;
  confidentialityNote?: string;
  disclaimerNote?: string;
  primaryColor?: string;
  secondaryColor?: string;
  isDefault?: boolean;
}

export interface AnnualReportStatus {
  totalSections: number;
  autoGeneratedSections: number;
  manuallyEditedSections: number;
  pendingSections: number;
  completionPercentage: number;
}

const reportService = {
  async getCatalog(): Promise<ReportCatalogItem[]> {
    const response = await apiClient.get('/report/catalog');
    return response.data;
  },

  async generateReport(data: GenerateReportRequest): Promise<GeneratedReport> {
    const response = await apiClient.post('/report/generate', data);
    return response.data;
  },

  async getHistory(reportTypeCode?: string, from?: string, to?: string): Promise<GeneratedReport[]> {
    const params = new URLSearchParams();
    if (reportTypeCode) params.append('reportTypeCode', reportTypeCode);
    if (from) params.append('from', from);
    if (to) params.append('to', to);
    const qs = params.toString();
    const response = await apiClient.get(`/report/history${qs ? '?' + qs : ''}`);
    return response.data;
  },

  async downloadReport(id: string): Promise<Blob> {
    const response = await apiClient.get(`/report/history/${id}/download`, {
      responseType: 'blob',
    });
    return response.data;
  },

  async getRecurringConfigs(): Promise<RecurringReportConfig[]> {
    const response = await apiClient.get('/report/recurring');
    return response.data;
  },

  async createRecurringConfig(data: CreateRecurringReportConfigRequest): Promise<RecurringReportConfig> {
    const response = await apiClient.post('/report/recurring', data);
    return response.data;
  },

  async pauseRecurringConfig(id: string): Promise<void> {
    await apiClient.post(`/report/recurring/${id}/pause`);
  },

  async resumeRecurringConfig(id: string): Promise<void> {
    await apiClient.post(`/report/recurring/${id}/resume`);
  },

  async getAnnualReportSections(): Promise<ManagementReportSection[]> {
    const response = await apiClient.get('/report/annual/sections');
    return response.data;
  },

  async updateAnnualReportSection(id: string, data: UpdateManagementReportSection): Promise<ManagementReportSection> {
    const response = await apiClient.put(`/report/annual/sections/${id}`, data);
    return response.data;
  },

  async regenerateSection(id: string): Promise<void> {
    await apiClient.post(`/report/annual/sections/${id}/regenerate`);
  },

  async getAnnualReportStatus(): Promise<AnnualReportStatus> {
    const response = await apiClient.get('/report/annual/status');
    return response.data;
  },

  async consolidateAnnualReport(fiscalYear: number): Promise<GeneratedReport> {
    const response = await apiClient.post('/report/annual/consolidate', { fiscalYear });
    return response.data;
  },

  async getTemplates(): Promise<PDFTemplate[]> {
    const response = await apiClient.get('/report/templates');
    return response.data;
  },

  async updateTemplate(id: string, data: UpdatePDFTemplate): Promise<PDFTemplate> {
    const response = await apiClient.put(`/report/templates/${id}`, data);
    return response.data;
  },
};

export default reportService;
