'use client';

import React, { useState, useEffect } from 'react';
import { Loader2, RefreshCw, FileText, ChevronDown, ChevronRight, Save } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';
import reportService, { ManagementReportSection, AnnualReportStatus } from '@/lib/report-service';
import axios from 'axios';

const statusBadgeClass: Record<string, string> = {
  AutoGenerated: 'badge-success',
  ManuallyEdited: 'badge-info',
  Pending: 'badge-warning',
};

const statusLabels: Record<string, string> = {
  AutoGenerated: 'Auto-generado',
  ManuallyEdited: 'Editado manualmente',
  Pending: 'Pendiente',
};

export default function AnnualPage() {
  const [sections, setSections] = useState<ManagementReportSection[]>([]);
  const [status, setStatus] = useState<AnnualReportStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');
  const [editTitle, setEditTitle] = useState('');
  const [saving, setSaving] = useState(false);
  const [fiscalYear, setFiscalYear] = useState<number>(new Date().getFullYear());
  const [consolidating, setConsolidating] = useState(false);
  const [regeneratingId, setRegeneratingId] = useState<string | null>(null);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    setError('');
    try {
      const [sectionsData, statusData] = await Promise.all([
        reportService.getAnnualReportSections(),
        reportService.getAnnualReportStatus(),
      ]);
      setSections(sectionsData);
      setStatus(statusData);
    } catch {
      setError('Error al cargar el informe anual.');
    } finally {
      setLoading(false);
    }
  };

  const handleEdit = (section: ManagementReportSection) => {
    setEditingId(section.id);
    setEditContent(section.content);
    setEditTitle(section.title);
  };

  const handleSaveSection = async () => {
    if (!editingId) return;
    setSaving(true);
    setError('');
    try {
      await reportService.updateAnnualReportSection(editingId, {
        title: editTitle,
        content: editContent,
      });
      setEditingId(null);
      setSuccess('Sección actualizada exitosamente.');
      fetchData();
    } catch (err) {
      if (axios.isAxiosError(err) && err.response?.data?.message) {
        setError(err.response.data.message);
      } else {
        setError('Error al guardar la sección.');
      }
    } finally {
      setSaving(false);
    }
  };

  const handleRegenerate = async (id: string) => {
    setRegeneratingId(id);
    setError('');
    try {
      await reportService.regenerateSection(id);
      setSuccess('Sección regenerada exitosamente.');
      fetchData();
    } catch (err) {
      if (axios.isAxiosError(err) && err.response?.data?.message) {
        setError(err.response.data.message);
      } else {
        setError('Error al regenerar la sección.');
      }
    } finally {
      setRegeneratingId(null);
    }
  };

  const handleConsolidate = async () => {
    setConsolidating(true);
    setError('');
    try {
      await reportService.consolidateAnnualReport(fiscalYear);
      setSuccess('Informe anual consolidado exitosamente.');
    } catch (err) {
      if (axios.isAxiosError(err) && err.response?.data?.message) {
        setError(err.response.data.message);
      } else {
        setError('Error al consolidar el informe.');
      }
    } finally {
      setConsolidating(false);
    }
  };

  const sortedSections = [...sections].sort((a, b) => a.sectionOrder - b.sectionOrder);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="w-8 h-8 animate-spin text-emerald-600" />
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold text-foreground">Informe de Gestión Anual</h1>

      {error && (
        <div className="p-4 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900 rounded-xl text-red-700 dark:text-red-400 text-sm">
          {error}
        </div>
      )}

      {success && (
        <div className="p-4 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900 rounded-xl text-emerald-700 dark:text-emerald-400 text-sm">
          {success}
        </div>
      )}

      {status && (
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-lg font-semibold text-foreground">Progreso del Informe</h2>
              <span className="text-2xl font-bold text-emerald-600">{status.completionPercentage}%</span>
            </div>
            <div className="w-full bg-muted rounded-full h-3">
              <div
                className="bg-emerald-600 h-3 rounded-full transition-all duration-500"
                style={{ width: `${status.completionPercentage}%` }}
              />
            </div>
            <div className="flex gap-4 mt-3 text-sm text-muted-foreground">
              <span>{status.totalSections} secciones totales</span>
              <span className="text-emerald-600">{status.autoGeneratedSections} auto-generadas</span>
              <span className="text-blue-600">{status.manuallyEditedSections} editadas</span>
              <span className="text-amber-600">{status.pendingSections} pendientes</span>
            </div>
          </CardContent>
        </Card>
      )}

      <div className="space-y-3">
        {sortedSections.map((section) => (
          <Card key={section.id}>
            <CardContent className="p-4">
              <div
                className="flex items-start justify-between cursor-pointer"
                onClick={() => setExpandedId(expandedId === section.id ? null : section.id)}
              >
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs text-muted-foreground">Sección {section.sectionOrder}</span>
                    <span className={`badge ${statusBadgeClass[section.status] || 'badge-neutral'}`}>
                      {statusLabels[section.status] || section.status}
                    </span>
                  </div>
                  <h3 className="font-semibold text-foreground">{section.title}</h3>
                </div>
                <div className="flex items-center gap-2 ml-4">
                  {expandedId === section.id ? (
                    <ChevronDown className="w-5 h-5 text-muted-foreground" />
                  ) : (
                    <ChevronRight className="w-5 h-5 text-muted-foreground" />
                  )}
                </div>
              </div>

              {expandedId === section.id && (
                <div className="mt-4 space-y-4">
                  {editingId === section.id ? (
                    <div className="space-y-3">
                      <div>
                        <label className="block text-sm font-medium text-foreground mb-1">Título</label>
                        <input
                          type="text"
                          value={editTitle}
                          onChange={(e) => setEditTitle(e.target.value)}
                          className="w-full border-b border-emerald-600/30 focus:border-emerald-600 text-sm font-medium py-2 outline-none bg-transparent"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-foreground mb-1">Contenido</label>
                        <textarea
                          value={editContent}
                          onChange={(e) => setEditContent(e.target.value)}
                          className="w-full border border-emerald-600/30 focus:border-emerald-600 text-sm font-medium py-2 outline-none rounded-lg px-3 bg-background min-h-[200px]"
                        />
                      </div>
                      <div className="flex gap-2">
                        <Button onClick={handleSaveSection} disabled={saving}>
                          <Save className="w-4 h-4 mr-1" />
                          {saving ? 'Guardando...' : 'Guardar'}
                        </Button>
                        <Button variant="secondary" onClick={() => setEditingId(null)}>
                          Cancelar
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <div>
                      <div className="text-sm text-foreground whitespace-pre-wrap">{section.content}</div>
                      <div className="flex gap-2 mt-4">
                        <Button variant="secondary" onClick={() => handleEdit(section)}>
                          Editar Sección
                        </Button>
                        {section.autoGeneratedQuery && (
                          <Button
                            variant="ghost"
                            onClick={() => handleRegenerate(section.id)}
                            disabled={regeneratingId === section.id}
                          >
                            <RefreshCw className={`w-4 h-4 mr-1 ${regeneratingId === section.id ? 'animate-spin' : ''}`} />
                            {regeneratingId === section.id ? 'Regenerando...' : 'Regenerar Sección'}
                          </Button>
                        )}
                      </div>
                      {section.lastAutoGeneratedAt && (
                        <p className="text-xs text-muted-foreground mt-2">
                          Última auto-generación: {new Date(section.lastAutoGeneratedAt).toLocaleDateString('es-CO')}
                        </p>
                      )}
                      {section.lastManualEditAt && (
                        <p className="text-xs text-muted-foreground">
                          Última edición manual: {new Date(section.lastManualEditAt).toLocaleDateString('es-CO')}
                        </p>
                      )}
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardContent className="p-6">
          <div className="flex items-center gap-4">
            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Año Fiscal</label>
              <input
                type="number"
                value={fiscalYear}
                onChange={(e) => setFiscalYear(parseInt(e.target.value) || new Date().getFullYear())}
                className="border-b border-emerald-600/30 focus:border-emerald-600 text-sm font-medium py-2 outline-none bg-transparent w-24"
                min={2020}
                max={2030}
              />
            </div>
            <Button onClick={handleConsolidate} disabled={consolidating}>
              <FileText className="w-4 h-4 mr-2" />
              {consolidating ? 'Consolidando...' : 'Consolidar Informe'}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
