using System;
using System.Collections.Generic;

namespace Softcoinp.ERP.WebAPI.DTOs;

public class ReportTypeDto
{
    public Guid Id { get; set; }
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string SourceModules { get; set; } = string.Empty;
    public string AllowedRoles { get; set; } = string.Empty;
    public bool ContainsPersonalData { get; set; }
    public bool IsActive { get; set; }
}

public class GeneratedReportDto
{
    public Guid Id { get; set; }
    public Guid ReportTypeId { get; set; }
    public string ReportTypeName { get; set; } = string.Empty;
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;
    public DateTime? PeriodFrom { get; set; }
    public DateTime? PeriodTo { get; set; }
    public string FileName { get; set; } = string.Empty;
    public long FileSizeBytes { get; set; }
    public string GeneratedByUserId { get; set; } = string.Empty;
    public string GeneratedByUserName { get; set; } = string.Empty;
    public DateTime GeneratedAt { get; set; }
    public string? Parameters { get; set; }
    public string? Notes { get; set; }
    public Guid? RecurringConfigId { get; set; }
}

public class GenerateReportRequestDto
{
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Format { get; set; } = "Pdf";
    public DateTime? PeriodFrom { get; set; }
    public DateTime? PeriodTo { get; set; }
    public string? Parameters { get; set; }
    public string? Notes { get; set; }
}

public class RecurringReportConfigDto
{
    public Guid Id { get; set; }
    public Guid ReportTypeId { get; set; }
    public string ReportTypeName { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Frequency { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;
    public string RecipientEmails { get; set; } = string.Empty;
    public string? SubjectTemplate { get; set; }
    public string? BodyTemplate { get; set; }
    public DateTime? LastExecutionAt { get; set; }
    public DateTime? NextExecutionAt { get; set; }
    public string Status { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
}

public class CreateRecurringReportConfigRequestDto
{
    public Guid ReportTypeId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Frequency { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;
    public string RecipientEmails { get; set; } = string.Empty;
    public string? SubjectTemplate { get; set; }
    public string? BodyTemplate { get; set; }
}

public class ManagementReportSectionDto
{
    public Guid Id { get; set; }
    public int SectionOrder { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
    public string? AutoGeneratedQuery { get; set; }
    public DateTime? LastAutoGeneratedAt { get; set; }
    public DateTime? LastManualEditAt { get; set; }
    public string? LastEditedByUserId { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

public class UpdateManagementReportSectionDto
{
    public string? Title { get; set; }
    public string? Content { get; set; }
    public int? SectionOrder { get; set; }
}

public class PDFTemplateDto
{
    public Guid Id { get; set; }
    public string ReportTypeCode { get; set; } = string.Empty;
    public string? LogoFilePath { get; set; }
    public string HeaderText { get; set; } = string.Empty;
    public string FooterText { get; set; } = string.Empty;
    public string SignatureName { get; set; } = string.Empty;
    public string SignatureRole { get; set; } = string.Empty;
    public string? ConfidentialityNote { get; set; }
    public string? DisclaimerNote { get; set; }
    public string PrimaryColor { get; set; } = "#059669";
    public string SecondaryColor { get; set; } = "#1e293b";
    public bool IsDefault { get; set; }
}

public class UpdatePDFTemplateDto
{
    public string? LogoFilePath { get; set; }
    public string? HeaderText { get; set; }
    public string? FooterText { get; set; }
    public string? SignatureName { get; set; }
    public string? SignatureRole { get; set; }
    public string? ConfidentialityNote { get; set; }
    public string? DisclaimerNote { get; set; }
    public string? PrimaryColor { get; set; }
    public string? SecondaryColor { get; set; }
    public bool? IsDefault { get; set; }
}

public class ReportCatalogItemDto
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public List<string> AvailableFormats { get; set; } = new() { "Pdf", "Excel" };
    public bool ContainsPersonalData { get; set; }
}

public class PortfolioAgingReportDto
{
    public List<PortfolioAgingBucketDto> Buckets { get; set; } = new();
    public decimal TotalOverdue { get; set; }
    public decimal TotalPaid { get; set; }
    public decimal GrandTotal { get; set; }
    public int UnitCount { get; set; }
}

public class PortfolioAgingBucketDto
{
    public string Label { get; set; } = string.Empty;
    public int FromDays { get; set; }
    public int ToDays { get; set; }
    public decimal TotalOverdue { get; set; }
    public decimal TotalPrincipal { get; set; }
    public decimal TotalInterest { get; set; }
    public int UnitCount { get; set; }
}

public class PQRSummaryReportDto
{
    public int TotalRequests { get; set; }
    public int OpenRequests { get; set; }
    public int ClosedRequests { get; set; }
    public int OverdueRequests { get; set; }
    public double AverageResponseTimeHours { get; set; }
    public List<PQRCategorySummaryDto> ByCategory { get; set; } = new();
}

public class PQRCategorySummaryDto
{
    public string Category { get; set; } = string.Empty;
    public int Count { get; set; }
    public double AverageResponseTimeHours { get; set; }
}

public class MaintenanceSummaryReportDto
{
    public int TotalPlanned { get; set; }
    public int ExecutedOnTime { get; set; }
    public int Overdue { get; set; }
    public decimal TotalEstimatedCost { get; set; }
    public decimal TotalActualCost { get; set; }
    public double CompliancePercentage { get; set; }
}

public class ContingencyFundReportDto
{
    public decimal CurrentBalance { get; set; }
    public decimal TotalContributions { get; set; }
    public decimal TotalUsages { get; set; }
    public List<ContingencyFundMovementDto> RecentMovements { get; set; } = new();
}

public class ContingencyFundMovementDto
{
    public DateTime Date { get; set; }
    public string Type { get; set; } = string.Empty;
    public string Concept { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public decimal RunningBalance { get; set; }
}

public class CollectionComparisonDto
{
    public decimal CurrentPeriodTotal { get; set; }
    public decimal PreviousPeriodTotal { get; set; }
    public decimal Variation { get; set; }
    public decimal VariationPercentage { get; set; }
}

public class AnnualReportStatusDto
{
    public int TotalSections { get; set; }
    public int AutoGeneratedSections { get; set; }
    public int ManuallyEditedSections { get; set; }
    public int PendingSections { get; set; }
    public double CompletionPercentage { get; set; }
    public DateTime? LastConsolidatedAt { get; set; }
}

public class AnnualReportConsolidatedDto
{
    public string TenantName { get; set; } = string.Empty;
    public string TenantNit { get; set; } = string.Empty;
    public int FiscalYear { get; set; }
    public List<ManagementReportSectionDto> Sections { get; set; } = new();
    public string GeneratedAt { get; set; } = string.Empty;
    public string GeneratedBy { get; set; } = string.Empty;
}
