using System;
using System.Collections.Generic;

namespace Softcoinp.ERP.WebAPI.DTOs;

public class ReportTypeDto
{
    public Guid Id { get; set; }
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string SourceModules { get; set; } = string.Empty;
    public string AllowedRoles { get; set; } = string.Empty;
    public bool ContainsPersonalData { get; set; }
    public bool IsActive { get; set; }
}

public class GeneratedReportDto
{
    public Guid Id { get; set; }
    public Guid ReportTypeId { get; set; }
    public string ReportTypeName { get; set; } = string.Empty;
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;
    public DateTime? PeriodFrom { get; set; }
    public DateTime? PeriodTo { get; set; }
    public string FileName { get; set; } = string.Empty;
    public long FileSizeBytes { get; set; }
    public string GeneratedByUserId { get; set; } = string.Empty;
    public string GeneratedByUserName { get; set; } = string.Empty;
    public DateTime GeneratedAt { get; set; }
    public string? Parameters { get; set; }
    public string? Notes { get; set; }
    public Guid? RecurringConfigId { get; set; }
    public int ConsecutiveNumber { get; set; }
}

public class GenerateReportRequestDto
{
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Format { get; set; } = "Pdf";
    public DateTime? PeriodFrom { get; set; }
    public DateTime? PeriodTo { get; set; }
    public string? Parameters { get; set; }
    public string? Notes { get; set; }
}

public class RecurringReportConfigDto
{
    public Guid Id { get; set; }
    public Guid ReportTypeId { get; set; }
    public string ReportTypeName { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Frequency { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;
    public List<string> RecipientEmails { get; set; } = new();
    public string? SubjectTemplate { get; set; }
    public string? BodyTemplate { get; set; }
    public DateTime? LastExecutionAt { get; set; }
    public DateTime? NextExecutionAt { get; set; }
    public string Status { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
}

public class CreateRecurringReportConfigRequestDto
{
    public string ReportTypeCode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Frequency { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;
    public List<string> RecipientEmails { get; set; } = new();
    public string? SubjectTemplate { get; set; }
    public string? BodyTemplate { get; set; }
}

public class ManagementReportSectionDto
{
    public Guid Id { get; set; }
    public int SectionOrder { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
    public string? AutoGeneratedQuery { get; set; }
    public DateTime? LastAutoGeneratedAt { get; set; }
    public DateTime? LastManualEditAt { get; set; }
    public string? LastEditedByUserId { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

public class UpdateManagementReportSectionDto
{
    public string? Title { get; set; }
    public string? Content { get; set; }
    public int? SectionOrder { get; set; }
}

public class ReportCatalogItemDto
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public List<string> AvailableFormats { get; set; } = new() { "Pdf", "Excel" };
    public bool ContainsPersonalData { get; set; }
}

public class AnnualReportStatusDto
{
    public int TotalSections { get; set; }
    public int AutoGeneratedSections { get; set; }
    public int ManuallyEditedSections { get; set; }
    public int PendingSections { get; set; }
    public double CompletionPercentage { get; set; }
    public DateTime? LastConsolidatedAt { get; set; }
}

public class ConsolidateAnnualReportRequestDto
{
    public int FiscalYear { get; set; }
}

public class AccountantExportRequestDto
{
    public DateTime PeriodFrom { get; set; }
    public DateTime PeriodTo { get; set; }
}
